[package]
name = "cosmic-applet-yt-dlp-dixycat"
version = "0.2.1"
edition = "2024"
authors = ["Dixycat <felix-the-cat177>"]
license = "GPL-3.0-only"
description = "A simple yt-dlp GUI for the COSMIC DE"

[dependencies]
ashpd = "0.11"
i18n-embed-fl = "0.9"
notify-rust = "4"
rust-embed = "8"
tokio = { version = "1", features = ["full"] }
url = "2"
xdg = "2.5"
xdg-user = "0.2"
yt-dlp = "2.8"

[dependencies.i18n-embed]
version = "0.15"
features = ["fluent-system", "desktop-requester"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["applet", "tokio", "wayland"]

# # Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }

[package.metadata.deb]
license-file = "LICENSE"
assets = [
    ["target/release/cosmic-applet-yt-dlp-dixycat", "usr/bin/", "755"],
    ["res/io.github.felix_the_cat177.CosmicAppletYtDlp.desktop", "usr/share/applications/", "644"],
    ["res/io.github.felix_the_cat177.CosmicAppletYtDlp.metainfo.xml", "usr/share/metainfo/", "644"],
]
depends = ["libc6", "liblzma5", "libssl3", "libxkbcommon0", "nscd"]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/cosmic-applet-yt-dlp-dixycat", dest = "/usr/bin/", mode = "755" },
    { source = "LICENSE", dest = "/usr/share/doc/cosmic-applet-yt-dlp-dixycat/LICENSE", doc = true, mode = "644" },
    { source = "res/*.metainfo.xml", dest = "/usr/share/metainfo/", doc = true, mode = "644" },
    { source = "res/*.desktop", dest = "/usr/share/applications/", mode = "644" }
]

[package.metadata.generate-rpm.requires]
glibc = "*"
libxkbcommon = "*"
nscd = "*"
openssl-libs = "*"
xz-libs = "*"
